# Generated by Django 5.1.4 on 2025-02-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
