# Generated by Django 5.1.4 on 2025-02-11 06:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_tripplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripplan',
            unique_together={('user', 'start_date')},
        ),
    ]
