# Generated by Django 5.1.4 on 2025-02-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_tripplan_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripplan',
            unique_together=set(),
        ),
    ]
