# Generated by Django 5.1.6 on 2025-03-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_trip_latitude_trip_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('booking_link', models.URLField()),
            ],
        ),
    ]
