# Generated by Django 5.1.6 on 2025-03-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_hotelimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='booking_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
