# Generated by Django 5.1.6 on 2025-03-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_hotel_rating_alter_hotel_booking_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelStaticInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_slot', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.DeleteModel(
            name='HotelImg',
        ),
    ]
