# Generated by Django 5.1.6 on 2025-03-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_hotelstaticinfo_alter_hotel_rating_delete_hotelimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelstaticinfo',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotelstaticinfo',
            name='hotel_slot',
            field=models.CharField(choices=[('slot_1', 'Best Hotel in the city'), ('slot_2', 'Best service Provided'), ('slot_3', 'Most Luxorious'), ('slot_4', 'Affordable Hotel Option'), ('slot_5', 'Best View')], max_length=10),
        ),
    ]
