# Generated by Django 5.1.6 on 2025-03-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_hotelstaticinfo_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelstaticinfo',
            name='image_url',
        ),
        migrations.AddField(
            model_name='hotelstaticinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AlterField(
            model_name='hotelstaticinfo',
            name='hotel_slot',
            field=models.CharField(choices=[('slot_1', 'Best Hotel in the city'), ('slot_2', 'Best service Provided'), ('slot_3', 'Most Luxurious'), ('slot_4', 'Affordable Hotel Option'), ('slot_5', 'Best View')], max_length=10),
        ),
    ]
