# Generated by Django 5.1.6 on 2025-03-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_remove_hotelstaticinfo_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNumber', models.CharField(max_length=100)),
                ('airline', models.CharField(max_length=100)),
                ('departureCity', models.CharField(max_length=100)),
                ('arrivalCity', models.CharField(max_length=100)),
                ('departureTime', models.DateTimeField()),
                ('arrivalTime', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
