# Generated by Django 5.1.6 on 2025-03-18 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbooking',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='arrivalTime',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='departureTime',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='flightNumber',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='route',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.flight'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
