# Generated by Django 5.1.6 on 2025-03-18 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_remove_flightbooking_airline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flightNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.flight'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
    ]
