# Generated by Django 5.1.6 on 2025-03-31 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_aiquestion_aigenerateditinerary_aioption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aioption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIGeneratedItinerary',
        ),
        migrations.DeleteModel(
            name='AIOption',
        ),
        migrations.DeleteModel(
            name='AIQuestion',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
