# Generated by Django 5.1.6 on 2025-03-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_remove_aioption_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('city', 'City'), ('days', 'Number of Days'), ('age_group', 'Age Group'), ('travel_companion', 'Travel Companion'), ('food_preference', 'Food Preference'), ('activity_type', 'Activity Preference'), ('place_type', 'Type of Places'), ('additional_notes', 'Additional Notes')], max_length=50)),
                ('options', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
