# Generated by Django 5.1.6 on 2025-03-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_open_ended',
            field=models.BooleanField(default=False),
        ),
    ]
