# Generated by Django 5.1.6 on 2025-04-04 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_review_delete_travelguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='required_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('city', 'City'), ('days', 'Number of Days'), ('age_group', 'Age Group'), ('travel_companion', 'Travel Companion'), ('food_preference', 'Food Preference'), ('activity_type', 'Activity Preference'), ('place_type', 'Type of Places'), ('additional_notes', 'Additional Notes'), ('budget', 'Budget')], max_length=50),
        ),
    ]
