# Generated by Django 5.1.6 on 2025-04-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_itinerary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itinerary',
        ),
    ]
