# Generated by Django 5.1.6 on 2025-04-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0032_itinerary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='HotelStaticInfo',
        ),
    ]
