# Generated by Django 5.1.6 on 2025-04-07 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0033_delete_hotel_delete_hotelstaticinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_description', models.TextField()),
                ('rate_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_class', models.CharField(max_length=50)),
                ('overall_rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('link', models.URLField()),
                ('image_url', models.URLField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
