# Generated by Django 5.1.6 on 2025-04-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0034_hotelbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
