# Generated by Django 5.1.6 on 2025-04-08 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0035_delete_hotelbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('rate_per_night', models.CharField(blank=True, max_length=50)),
                ('hotel_class', models.CharField(blank=True, max_length=50)),
                ('overall_rating', models.CharField(blank=True, max_length=10)),
                ('reviews', models.TextField(blank=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('image_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
