# Generated by Django 5.1.6 on 2025-04-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0038_hotelbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
