# Generated by Django 5.1.6 on 2025-04-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0041_saveditinerary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedItinerary',
        ),
    ]
